{
 "title": "FTM Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ftm_block, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_block{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ftm_address_balance{address=\"0x120Af64d9B7bB555cd2Abc47A945d126ddeD0376\",instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Ether Transfers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_eth_transfers{instance=\"${instance:string}\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "ftm_token_transfers{instance=\"${instance:string}\"}",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "ETH Value",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_block_value{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_seconds_last_block{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_block_transactions{instance=\"${instance:string}\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_eth_transfers{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Token Transfers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_token_transfers{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_pending_transactions{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ftm_block_size_bytes{instance=\"${instance:string}\"}",
     "legendFormat": "Token Transfers"
    }
   ]
  },
  {
   "title": "Gas Price (gwei)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ftm_gas_price{instance=\"${instance:string}\"} / 1000000000",
     "legendFormat": "Gas Price"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_gas_price{instance=\"${instance:string}\"} / 1000000000"
    }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_eth_transfers{instance=\"${instance:string}\"}",
     "legendFormat": "ETH Transfers"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ftm_block_gas_used{instance=\"${instance:string}\"}",
     "legendFormat": "Token Transfers"
    }
   ]
  },
  {
   "title": "Contracts Created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_contracts_created{instance=\"${instance:string}\"}",
     "legendFormat": "Contracts"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "ftm_load_time{instance=\"${instance:string}\"}"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_block_difficulty{instance=\"${instance:string}\"} / 10000000000000",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_block_nonce{instance=\"${instance:string}\"} / 1000000000000000000",
     "legendFormat": "Nonce"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_pending_transactions{instance=\"${instance:string}\"}",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<p align=\"center\" style=\"font-size:30pt\">Today Totals</p>"
   }
  },
  {
   "title": "Today's Sent ETH",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 34 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(ftm_block_value{instance=\"${instance:string}\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 34 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "ftm_block_transactions{instance=\"${instance:string}\"}",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}