name: Build exporter
on:
  push:
    branches:
      - master
      - fantom
  pull_request:
    branches:
      - master
jobs:
  build:
    name: "Build exporter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.10"
      - run: go build main.go
      - uses: actions/download-artifact@v2
        with:
          name: gethexporter
